os: linux
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc

jobs:
  fast_finish: true
  include:
    - &test_body
      env:
        - TEST_CASE=tests/onenet TARGET=uhdm/verilator/test-ast
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      before_install:
        - eval "CC=gcc-7 && CXX=g++-7"
        # UHDM dependencies
        - sudo apt-get install build-essential tclsh
        # Surelog dependencies
        - sudo apt install ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev
        - git submodule update --init --recursive
      script:
        - make TEST=$TEST_CASE $TARGET

    - <<: *test_body
      env:
        - TEST_CASE=tests/onenet TARGET=uhdm/yosys/test-ast

    - <<: *test_body
      env:
        - TEST_CASE=tests/onenet TARGET=uhdm/vcddiff

    - <<: *test_body
      env:
        - TEST_CASE=tests/OneNetModport TARGET=uhdm/verilator/test-ast

    - <<: *test_body
      env:
        - TEST_CASE=tests/OneNetModport TARGET=uhdm/yosys/test-ast

    - <<: *test_body
      env:
        - TEST_CASE=tests/OneNetModport TARGET=uhdm/vcddiff
