name: 'main'

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build-binaries:
    runs-on: ubuntu-latest
    env:
      CC: gcc-9
      CXX: g++-9

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
         python-version: '3.7'

    - name: Build binaries
      run: |
        make -j$(nproc) prep
        # By default actions/upload-artifact@v2 do not preserve file permissions
        # tar directory to workaround this issue
        # See https://github.com/actions/upload-artifact/issues/38
        tar -cvf binaries.tar image

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: binaries.tar

  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
           python-version: '3.7'

      - name: Generate matrix
        id: generate-matrix
        run: |
          matrix="$(python list.py -d tests -s ibex yosys synthesis OneClass hello-uvm)"
          echo "::set-output name=matrix::$matrix"
          echo "Matrix: $matrix"

  generate-ibex-modules:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-ibex-modules.outputs.matrix }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
           python-version: '3.7'

      - name: Generate matrix
        id: generate-ibex-modules
        run: |
          matrix="$(python list.py -d tests/ibex/module_tests)"
          echo "::set-output name=matrix::$matrix"
          echo "Matrix: $matrix"

  tests:
    runs-on: ubuntu-latest
    needs: [build-binaries, generate-matrix]
    strategy:
      matrix:
        TEST_CASE: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
        TARGET:
          - uhdm/yosys/test-ast
          - uhdm/verilator/test-ast
          - uhdm/vcddiff
      fail-fast:
        false
    env:
      CC: gcc-9
      CXX: g++-9
      GIT_HTTP_LOW_SPEED_LIMIT: 1
      GIT_HTTP_LOW_SPEED_TIME: 600

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
         python-version: '3.7'

    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries

    # See https://github.com/actions/upload-artifact/issues/38
    - name: Extract
      run: tar -xf binaries.tar

    - name: Build & Test
      run: ./.github/ci.sh
      env:
        TEST_CASE: ${{ matrix.TEST_CASE }}
        TARGET: ${{ matrix.TARGET }}


  ibex-module-tests:
    runs-on: ubuntu-latest
    needs: [build-binaries, generate-ibex-modules]
    strategy:
      matrix:
        TEST_CASE: ${{ fromJson(needs.generate-ibex-modules.outputs.matrix) }}
        TARGET:
          - uhdm/verilator/test-ast
      fail-fast:
        false
    env:
      CC: gcc-9
      CXX: g++-9
      GIT_HTTP_LOW_SPEED_LIMIT: 1
      GIT_HTTP_LOW_SPEED_TIME: 600

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
         python-version: '3.7'

    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries

    # See https://github.com/actions/upload-artifact/issues/38
    - name: Extract
      run: tar -xf binaries.tar

    - name: Build & Test
      run: |
        pip install virtualenv
        virtualenv venv-ibex
        . venv-ibex/bin/activate
        pip install -r tests/ibex/ibex/python-requirements.txt
        cd tests/ibex/ibex
        fusesoc --cores-root=. run --target=synth --setup lowrisc:ibex:top_artya7 --part xc7a35ticsg324-1L
        cd ../../..
        ./.github/ci.sh
      env:
        TEST_CASE: ${{ matrix.TEST_CASE }}
        TARGET: ${{ matrix.TARGET }}


  surelog-uhdm:
    runs-on: ubuntu-latest
    env:
      CC: gcc-9
      CXX: g++-9

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
         python-version: '3.7'

    - name: Build & Test
      run: ./.github/ci.sh
      env:
        MODE: surelog-uhdm

  ibex_synth:
    runs-on: ubuntu-latest
    needs: build-binaries
    strategy:
      matrix:
        TARGET: [uhdm/yosys/synth-ibex]
      fail-fast:
        false
    env:
      CC: gcc-9
      CXX: g++-9

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
         python-version: '3.7'

    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries

    # See https://github.com/actions/upload-artifact/issues/38
    - name: Extract
      run: tar -xf binaries.tar

    - name: Build & Test
      run: |
        pip install virtualenv
        ./.github/ci.sh
      env:
        TARGET: uhdm/yosys/synth-ibex
        TEST_CASE: tests/ibex

    - uses: actions/upload-artifact@v2
      with:
        name: lowrisc_ibex_top_artya7_surelog_0.1.edif
        path: build/lowrisc_ibex_top_artya7_surelog_0.1/synth-yosys/lowrisc_ibex_top_artya7_surelog_0.1.edif

  simple-system-sim:
    runs-on: ubuntu-latest
    needs: build-binaries
    env:
      CC: gcc-9
      CXX: g++-9

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
         python-version: '3.7'

    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries

    # See https://github.com/actions/upload-artifact/issues/38
    - name: Extract
      run: tar -xf binaries.tar

    - name: Build & Test (uhdm verilator)
      run: |
        pip install virtualenv
        ./.github/ci.sh
        ./build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/Vibex_simple_system --meminit=ram,hello_test.elf
        mkdir output_uhdm
        cp ibex_simple_system.log ibex_simple_system_pcount.csv trace_core_00000000.log output_uhdm/
      env:
        TARGET: surelog-ibex
        TEST_CASE: tests/ibex

    - name: Build & Test (vanilla verilator)
      run: |
        pip install virtualenv
        ./.github/ci.sh
        ./build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/Vibex_simple_system --meminit=ram,hello_test.elf
        diff -y ibex_simple_system.log output_uhdm/ibex_simple_system.log
      env:
        TARGET: surelog-ibex-verilator
        TEST_CASE: tests/ibex

    - uses: actions/upload-artifact@v2
      with:
        name: simple-system-simulation-output
        path: output_uhdm
